cd .\utility\
schange bytecomposition.src
schange runtimefieldmanager.src
schange filereadwrite.src
cd ..\word\
schange dynamic.src
schange calc.src
schange inspect_character.src
schange integer.src
schange check.src
schange if.src
cd ..\runtimefield\
schange runtimefieldClass.src
schange runtimefieldNameAndType.src
schange runtimefieldMethod.src
schange runtimefieldField.src
cd ..
schange debug.src
schange compiler.src
schange functiontype.src
schange opecode.src
schange utf8rap.src

umind jmindc.src